### ISSUE TITLE
More gems are needed

### ISSUE THREAD

**Issue by swt2public** [swt2-intro-exercise/rails-exercise-22-Sohn123#2]
The ruby mine has run out of gems.

Please add more gems to your Gemfile. Thanks!

Best regards,
your Rails team.

**Comment by Sohn123** [comment]
Dear rails team,
I think my gemfile looks perfectly fine. Which gems would you recommend?

**Comment by swt2public** [comment]
Hi,
we would recommend diffy, because it is a great gem.
Version 3.4.0 seems especially nice.
Best regards,
Your Rails team
